[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.10.0"

[[constraint]]
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
